name: CI for 4.x

on:
  push:
    branches: [ 4.x ]
  pull_request:
    branches: [ 4.x ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      version: '18.19.0, 18, 20, 22, 23'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
